### ISSUE TITLE
Graphics Enhancements

### ISSUE THREAD

**Issue by toby63** [seedhartha/reone#6]
Hello,

I am watching all of these open source engines for Bioware's classics with great interest :+1:.

My Question is about whether graphical improvements are a) possible and b) "planned" (whatever that means in terms of huge freetime projects), because I always hoped to see this (beyond only HD Textures).
(Sidequestion: I guess HD-Textures are or will be possible to use?)

For those asking what I mean; I am thinking of many potencial things:
- Better Illumination - this alone can have a huge effect, just look at the Quake 3 Raytracing videos for example
- Shaders
- Tessellation - looked interesting, for example [article about graphics improvements for deus ex including hardware tesselation](https://www.dsogaming.com/news/dx11-renderer-released-for-unreal-deus-ex-supporting-pom-hardware-tesselation-more/)
(Or is it already built-in in the original vanilla game :smile:?, the objects and grounds always look so flat)
- Environments Improvements - No idea if this is really an engine thing (normally it is of course related to modding (adding objects, models etc.)), but whenever I look at Kotor again I always think 'Well the character models look old but ok, but the environment looks so empty', so maybe some things could improve:
    - Grass and trees and stuff could be added "automatically" (based on terrain or similar) (just a silly idea from a man who has no clue :smile:)
    - "Moving" grass and trees would look awesome.

People with some knowledge in that area could probably name more accurate terms for this, but I don't know much about it :sweat_smile:.

Still I am interested in your oppinion on my ideas :wink:.

**Comment by pkurras** [comment]
I wanna add to the post by @seedhartha with respect to environmental improvements since I have some experience with that:

**Procedural foliage** which you refer to as "Grass and trees and stuff could be added automatically" is a technique that is applied on terrain with special textures. So when you have a rocky area there would be different kinds of foliage. However, if there's another object on that terrain, at that location nothing is to be generated so that there are no ugly object intersections. Normally, you'd also have to have some sort of settings for that generation since you'd have multiple kinds of objects that could be spawned. For instance: flowers, grass, pebbles, mushrooms, etc. and you need a way to control the spawn probability. But that's overkill for such a project. This sounds more appropriate for a remake and you'd need to do much bigger things first to improve the visual fidelity.

**Foliage wind** or **vertex wind** which you're referring to as "Moving grass and trees" would be possible with very small effort. But data is the problem. The objects have very few vertices and to have a good wind effect you'd need to have more of them. In addition, you'd need to have associate data that classifies which vertex should have which "base".
A **base** in that sense is some sort of movement origin where the movement is smallest. Then you can calculate the wind effect based on the distance to its hierarchical origin. This is needed since you want the leaves to also move with the branches and the trunk. Then ofc. the branches do their own plus the trunk movement and, finally, the trunk just does its own movement.
So a foliage vertex would need at least **one vertex position** and **three base bone positions**. Depending on the distance to the bone positions that would affect their movement. If the distance is 0.0f then the movement is stripped. For instance, for the trunk, there would be no distance in the branch and leave bone positions so that the shader knows "this is a trunk vertex".
You'd need to supply this bone rig data which means editing each and every piece of foliage, storing the data separate from the models (since original assets are not to be touched). Apart from a custom format and the editing effort, nobody can say how it would look in the game without trying. So this is a rabbit hole all over again.

**Comment by toby63** [comment]
@seedhartha @pkurras Interesting. Thx for the information so far :+1:.

From what I heard now I guess shaders are the most realistic option.
But who knows, maybe some more developers and modders will participate, once the engine works well.
With your approval I will leave this open, to collect some ideas and comments.

**Comment by pkurras** [comment]
@toby63 Shaders are another fancy word of telling the graphics card what to do. Shaders are programs that define where the vertices of a mesh are rendered and what color the resulting pixels get after the rasterization of the camera view. So literally **every** 3D application uses shaders. They just can be more or less complex in that matter. In the old days, you couldn't create your own shaders since their functionality was hardcoded on the GPU so every game looked the same but today we have that option. That's the difference.

**Comment by toby63** [comment]
@pkurras For me it's about better illumination, I don't know enough about technical details to understand the differences between what is what exactly.
